version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
      - "node_modules:/app/node_modules"
    command: npm run develop -- --host 0.0.0.0

volumes:
  node_modules:
